/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test
//    void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }

    @Test
    void testQuote() {
        Quote test= new Quote();
        try {
            assertEquals("Quote{" + "author='" + test.getAuthor() + '\''
                    + ", text='" + test.getText() + '\'' + '}',
                    App.getInfQuote(), "xxxxxxxxxxxxxxxxxxxxxxxx");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
