/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.common.reflect.TypeToken;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Random;

public class App {


    public static void main(String[] args) throws FileNotFoundException {
        System.out.println(getInfQuote());

    }


    public static String getInfQuote() throws FileNotFoundException {
        Gson gson = new Gson();
        Reader reader = new FileReader("app/src/main/resources/file.json");

        Type listType = new TypeToken<List<Quote>>() {
        }.getType();
        List<Quote> booksList = gson.fromJson(reader, listType);


        Random random = new Random();
        int randomNum = random.nextInt((booksList.size() - 1) + 1);
        return booksList.get(randomNum).toString();

    }
}
